channels:
- conda-forge
dependencies:
- python=3.13.3
- pip<=25.2
- pip:
  - mlflow==3.1.1
  - cloudpickle==3.1.1
  - numpy==2.3.1
  - pandas==2.2.3
  - pathlib==1.0.1
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.15.2
name: mlflow-env
